version: '3'

services:
  lms-container:
    image: postgres:latest
    container_name: lms-container
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lms

  lms-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lms-api
    ports:
      - '3000:3000'
    depends_on:
      - lms-container
    environment:
      DATABASE_URL: postgres://postgres:postgres@lms-container:5432/lms
